### ISSUE TITLE
2.7.1 Non functional

### ISSUE THREAD

**Issue by Semiote** [Dirtywave/M8HeadlessFirmware#10]
Just flashed my Teensy 4.1 with the newest firmware, was working fine, but now it slowly blinks in program mode and won't connect the the Designer UI. USB audio devices are registering in windows, showing that the device is not in bootloader mode.

Reverting to 2.7.0, everything works again.

**Comment by trash80** [comment]
Try flashing again. Do not use Web display (and close it) if that is what you used to flash it.

**Comment by Semiote** [comment]
I flash with the native desktop Teensy.exe official flasher.

Just tried 2.7.1.A and it's working now, thanks for the fast turn around!
