### ISSUE TITLE
 Request: source code availalble for people to make changes on it anjd handle Teensy pinout

### ISSUE THREAD

**Issue by theshinyknight** [Dirtywave/M8HeadlessFirmware#12]
I am glad to see that this project exist, and I am aware that if there was a complete open project, people would make their own device; so to an extent I can related with the reluctant disposition to dedicate too much time on this "free" project, as it require a lot of time to test configurations and potentially would end up taking too much time to the main developer.

As such; since the problem was stated as lack of time and desire to support the project, due to the many things that could go wrong if people make their M8; making the source code available for the headless would solve these issues.

As the project use a Teensy; which is open hardware, and has most people familiar with its IO and architecture can handle by themselves the various issues that may arise if the code was available, this could help the main developer to focus on his hardware product for most part.

I exclude that in the entire codebase there is something that can be considered confidential, as a teardown of the M8 show clearly which parts have been used, and the code to address these parts and the related libraries are open source; so if there is anything that could be covered by a trademark or patent can be easily obfuscated.

Personally I think that having the ability to deal with pins on the Teensy to add or remove things to the headless M8 version would be welcome by many people; and for the ones concerned about "loss of sales"; I would point out that most people can't even solder the header on a teensy; so the chance that someone would make a DIY without have the skills to do so, compared to buy the actual product would be close to 0.0

**Comment by rspilk** [comment]
Id  love to see either source code or at least a compiled version for something other than the ARM Cortex M7. Preferably something that could run in qemu. Seems so weird that there hasn't been any discussion about how weird it is to connecting to a physical teensy 4.1 to do the processing

**Comment by rspilk** [comment]
For reference, I have attempted to run the released firmware in qemu since it is supposed to have some support for the chip:

# Generate .elf
arm-none-eabi-objcopy -I ihex -O elf32-littlearm -B arm M8_V3_2_7_HEADLESS.hex M8.elf

# Run qemu
qemu-system-arm -cpu cortex-m7 -machine mps2-an500 -kernel M8.elf

I've not gotten this to run for me and it returns a core dump
qemu: fatal: Lockup: can't escalate 3 to HardFault (current priority -1)

**Comment by trash80** [comment]
It is not open source. Headless is available to try out M8, or for people who cannot afford the hardware as all the features of what makes headless possible is already in the M8 hardware itself, making support and development easy. There is no current roadmap for porting M8.

**Comment by theshinyknight** [comment]
> It is not open source. Headless is available to try out M8, or for people who cannot afford the hardware as all the features of what makes headless possible is already in the M8 hardware itself, making support and development easy. There is no current roadmap for porting M8.

Understood; so if I want to make my own device instead of paying a scalper 1000 dollars I can't do that. The only alternative is to make a headless one and pack it with another device at that point.

If you would release at least the BOM and the gerber files so people can make their own, or even sell kits, this would really be a great thing. After all you get no profit from people scalping others with your product, so would be in your interest to support your buyers at that point, and at the same time you would crash those people that profit from reselling your device at insane prices.
